# -*- coding: utf-8 -*-
"""Load Monitoring.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s53I4eXmkbzn54-EQSVTb96Mnj3McRYE
"""

from google.colab import files
import pandas as pd
import matplotlib.pyplot as plt

# Upload the file (popup will appear)
uploaded = files.upload()

training_data = pd.read_csv("soccer_training.csv")

training_data.describe()
training_data["Session_Load"]=training_data["Duration_min"]*training_data["sRPE"]
training_data["Date"]=pd.to_datetime(training_data["Date"])
training_data

training_data["Week"]=training_data["Date"].dt.isocalendar().week
weekly_load = training_data.groupby(["Player", "Week"])["Session_Load"].sum().reset_index()

print("Weekly Training Load:")
print(weekly_load)

pivot = weekly_load.pivot(index="Player", columns="Week", values="Session_Load").fillna(0)
print(pivot.head())

pivot.plot(kind="bar", figsize=(14,6))
plt.ylabel("Training Load (AU)")
plt.xlabel("Player")
plt.title("Weekly Training Load per Player")
plt.legend(title="Week", bbox_to_anchor=(1.05, 1))
plt.show()